config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetings, only: %i[create show update new edit destroy] do
    resources :meeting_members, only: %i[create destroy]
    resources :bets, only: %i[index create destroy]
  end
  get '/my_meetings', to: 'meetings#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  get '/sign_out', to: 'sessions#destroy'

  root 'home#index'
end

app/models/meeting.rb
# frozen_string_literal: true

class Meeting < ApplicationRecord
  BASE_SCORE = 100
  self.implicit_order_column = 'created_at'

  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :meeting_members, dependent: :destroy
  has_many :users, through: :meeting_members
  has_one_attached :transcript

  before_create :add_creator_as_member

  def begun?
    Time.zone.now > start_at
  end

  def compute_score
    bets = Bet.where(meeting: self)
    score_by_bet = bets.group_by { |bet| bet.text.downcase }.transform_values { |bet_array| BASE_SCORE/bet_array.size }
    return {} if transcript_text.nil?

    users.each_with_object({}) do |user, scores|
      scores[user.email] = compute_user_score(bets.where(user_id: user.id), transcript_text, score_by_bet)
    end
  end

  private

  def add_creator_as_member
    users << creator
  end

  def compute_user_score(bets, script, score_by_bet)
    count_occurences(bets.map(&:text), script)
      .map { |bet, occurence_count| score_by_bet[bet] * bet.split.size * occurence_count }.sum
  end

  def count_occurences(bets, script)
    script = script.downcase.gsub(/[[:punct:]]+/, ' ').gsub(/ +/, ' ')
    bets_score = bets.map!(&:downcase).index_with(0)

    candidates = {}

    script.split.each do |script_word|
      remaining_candidates = candidates
      candidates = {}

      remaining_candidates.each do |left, candidate_bet|
        if left == script_word
          bets_score[candidate_bet] += 1
          next
        end
        if left =~ /^#{script_word} /
          left = left.gsub(/^#{script_word} /, '')
          candidates[left] = candidate_bet
        end
      end

      bets.each do |candidate_bet|
        if candidate_bet == script_word
          bets_score[candidate_bet] += 1
          next
        end
        if candidate_bet =~ /^#{script_word} /
          left = candidate_bet.gsub(/^#{script_word} /, '')
          candidates[left] = candidate_bet
        end

      end
    end
    bets_score
  end
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[show]
  before_action :set_meeting_for_creator, only: %i[edit update destroy]
  before_action :only_creator, only: %i[edit update destroy]

  # GET /meetings or /meetings.json
  def index
    @meetings = current_user.meetings.order(start_at: :desc)
  end

  # GET /meetings/1 or /meetings/1.json
  def show
    @my_bets = current_user.bets_on(@meeting) if current_user.member_of?(@meeting)
    @other_bets = Bet.where(meeting: @meeting).where.not(user:current_user)
    @new_bet = Bet.new
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = new_meeting_from_params

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meeting_url(@meeting), notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    if meeting_params[:transcript]
      @meeting.transcript.purge
      @meeting.transcript_text = meeting_params[:transcript].read
    end
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy!

    respond_to do |format|
      format.html { redirect_to my_meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def only_creator
    redirect_to root_url unless @meeting.creator == current_user
  end

  private

  def new_meeting_from_params
    meeting = Meeting.new(meeting_params)
    meeting.creator = current_user
    meeting
  end

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def set_meeting_for_creator
    @meeting = Meeting.where(creator: current_user).find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:title, :start_at, :end_at, :transcript)
  end
end

app/views/meetings/_bet_section.html.slim
.grid.grid-cols-1.gap-4.sm:grid-cols-2
  - bets.each do |bet|
    .relative.rounded-lg.border.border-gray-300.bg-white.px-6.py-5.shadow-sm.flex.items-center.space-x-3.hover:border-gray-400.focus-within:ring-2.focus-within:ring-offset-2.focus-within:ring-indigo-500
      .flex-1.min-w-0
        p.text-sm.font-medium.text-gray-900
          = "\"#{bet.text}\""
        p.text-sm.text-gray-500.truncate
          = "#{bet.text.split.count} words"
        - if other
          p.text-sm.text-gray-500.truncate
            = "#{bet.user.to_s}"
      - unless other
        = button_to 'X',   meeting_bet_path(@meeting, bet), method: :delete

app/views/meetings/_form.html.slim
= simple_form_for(meeting, class: 'space-y-8 divide-y divide-gray-200') do |f|
  .space-y-8.divide-y.divide-gray-200.sm:space-y-5
    div
      div
        p.mt-1.max-w-2xl.text-sm.text-gray-500
          |  This information will be displayed publicly so be careful what you share.
      .mt-6.sm:mt-5.space-y-6.sm:space-y-5
        = f.input :title, label_html: { class: 'block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2' }, input_html: { class: 'block max-w-lg w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm border-gray-300 rounded-md'}, wrapper_html: {class: 'sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5'}

        .sm:grid.sm:grid-cols-3.sm:gap-4.sm:items-start.sm:border-t.sm:border-gray-200.sm:pt-5
          label.block.text-sm.font-medium.text-gray-700.sm:mt-px.sm:pt-2
            | Start at
          div
            = f.input :start_at, label: false, wrapper: false, input_html: { class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm border-gray-300 rounded-md'}
        .sm:grid.sm:grid-cols-3.sm:gap-4.sm:items-start.sm:border-t.sm:border-gray-200.sm:pt-5
          label.block.text-sm.font-medium.text-gray-700.sm:mt-px.sm:pt-2
            | End at
          div
            = f.input :end_at, label: false, wrapper: false, input_html: { class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm border-gray-300 rounded-md'}

        .sm:grid.sm:grid-cols-3.sm:gap-4.sm:items-start.sm:border-t.sm:border-gray-200.sm:pt-5
          label.block.text-sm.font-medium.text-gray-700.sm:mt-px.sm:pt-2
            | transcript
          div.flex-col
            div.my-5
              - if meeting.transcript_text.present?
                = "The transcript has been already uploaded"
            = f.input :transcript, label: false, wrapper: false, input_html: { class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm border-gray-300 rounded-md'}

  .pt-5
    .flex.justify-center
      - back_path = meeting.persisted? ? meeting_path(meeting) : my_meetings_path
      = link_to 'Cancel', back_path, class: 'bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500'
      = f.button :submit, class: 'ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500'

- if meeting.persisted?
  = simple_form_for(meeting, method: 'DELETE') do |f|
    .form-actions
      = f.button :submit, 'DELETE', class: 'ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500'

app/views/meetings/edit.html.slim
== render 'form', meeting: @meeting

app/views/meetings/index.html.slim
header.bg-white.px-4.py-5.border-b.border-gray-200.sm:px-6
  .-ml-4.-mt-4.flex.justify-between.items-center.flex-wrap.sm:flex-nowrap
    .ml-4.mt-4
      h1.text-2xl.leading-6.font-medium.text-gray-900
        | My Meetings
    .ml-4.mt-4.flex-shrink-0
      = link_to 'New Meeting', new_meeting_path, class: "relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"


.flex.flex-col
  .-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
    .py-2.align-middle.inline-block.min-w-full.sm:px-6.lg:px-8
      .shadow.overflow-hidden.border-b.border-gray-200.sm:rounded-lg
        table.min-w-full.divide-y.divide-gray-200
          thead.bg-gray-50
            tr
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Title
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Start at
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Creator
              th
          tbody.bg-white.divide-y.divide-gray-200
            - @meetings.each do |meeting|

              tr
                td.px-6.py-4.whitespace-nowrap.text-sm.font-medium.text-gray-900
                  = link_to meeting.title, meeting, class: 'text-indigo-600 hover:text-indigo-900'
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  = meeting.start_at
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  = meeting.creator
                td.px-6.py-4.whitespace-nowrap.text-right.text-sm.font-medium
                  - if meeting.creator == current_user
                    = link_to 'Edit', edit_meeting_path(meeting), class: 'text-indigo-600 hover:text-indigo-900'

app/views/meetings/new.html.slim
h1 New meeting

== render 'form', meeting: @meeting

app/views/meetings/show.html.slim
main.mt-4.pb-8
  .max-w-3xl.mx-auto.px-4.sm:px-6.lg:max-w-7xl.lg:px-8
    .grid.grid-cols-1.gap-4.items-start.lg:grid-cols-3.lg:gap-8
      .grid.grid-cols-1.gap-4.lg:col-span-2
        section[aria-labelledby="section-1-title"]
          h2#section-1-title.sr-only
            = "My bets"
          .rounded-lg.bg-white.overflow-hidden.shadow
            .p-6
              - if current_user.member_of?(@meeting)
                = "My bets (#{@my_bets.count}/#{Bet::MAX_BET_PER_MEETING})"
                - if @my_bets.empty?
                  .relative.italic.bg-white.px-6.py-5.shadow-sm.flex.items-center.space-x-3.hover:border-gray-400.focus-within:ring-2.focus-within:ring-offset-2.focus-within:ring-indigo-500
                    | You made no bet for the moment

                - else
                  =render 'bet_section', bets: @my_bets, other: false
                - if @my_bets.count < Bet::MAX_BET_PER_MEETING && !@meeting.begun?
                  .relative.rounded-lg.border.border-gray-300.bg-white.px-6.py-5.shadow-sm.flex.items-center.space-x-3.my-5
                    = simple_form_for [@meeting, @new_bet] do |f|
                        p.text-sm.font-medium.text-gray-900
                          = f.input :text, label: false, wrapper: false
                          = f.button :submit, class: 'relative inline-flex items-center px-2 py-1 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mx-4'
              - else
                = button_to 'Join the meeting', meeting_meeting_members_path(meeting_id: @meeting.id, method: :post), class: 'relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-xl font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500'
          h2#section-1-title.sr-only
            = "Other bets"
          .rounded-lg.bg-white.overflow-hidden.shadow.my-5
              .p-6
                - if current_user.member_of?(@meeting)
                  = "Other bets (#{@other_bets.count}/#{Bet::MAX_BET_PER_MEETING})"
                  - if @other_bets.empty?
                    .relative.italic.bg-white.px-6.py-5.shadow-sm.flex.items-center.space-x-3.hover:border-gray-400.focus-within:ring-2.focus-within:ring-offset-2.focus-within:ring-indigo-500
                      | Others made no bets yet.

                  - else
                    =render 'bet_section', bets: @other_bets, other: true
      .grid.grid-cols-1.gap-4
        section[aria-labelledby="section-2-title"]
          h2#section-2-title.sr-only
            | Section title
          .rounded-lg.bg-white.overflow-hidden.shadow
            .p-6
              p.text-lg.font-bold
                = @meeting.title

              p
                = "#{@meeting.start_at.to_formatted_s(:short)} - #{@meeting.end_at.to_formatted_s(:short)}"

              p
                | created by:&nbsp;
                = @meeting.creator
              p.py-2.flex.justify-center
                => link_to 'Edit', edit_meeting_path(@meeting), class: 'ml-3 inline-flex justify-center py-1 px-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' if @meeting.creator == current_user
        - if @meeting.transcript_text.present?
          .grid.grid-cols-1.gap-4
            section[aria-labelledby="section-2-score"]
              h2#section-2-score.sr-only
                | Section score
              .rounded-lg.bg-white.overflow-hidden.shadow
                .p-6
                  p.text-lg.font-bold
                    = 'Scores'

                  ol
                    - @meeting.compute_score.each do |user, score|
                      li
                        = "#{user.to_s} - #{score}"