config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetings, only: %i[create show update new edit destroy] do
    resources :meeting_members, only: %i[create destroy]
    resources :bets, only: %i[index create destroy]
  end
  get '/my_meetings', to: 'meetings#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  get '/sign_out', to: 'sessions#destroy'

  root 'home#index'
end

app/views/layouts/_notices.html.slim
- if flash[:notice]
  .rounded-md.bg-green-50.p-4
    .flex
      .flex-shrink-0
        svg.h-5.w-5.text-green-400[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
          path[fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"]
      .ml-3
        p.text-sm.font-medium.text-green-800
          = flash[:notice]
      .ml-auto.pl-3
        .-mx-1.5.-my-1.5
          button.inline-flex.bg-green-50.rounded-md.p-1.5.text-green-500.hover:bg-green-100.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-offset-green-50.focus:ring-green-600[type="button"]
            span.sr-only
              | Dismiss
            svg.h-5.w-5[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
              path[fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"]

app/views/layouts/application.html.slim
doctype html
html.h-full.bg-gray-100
  head
    title
      | Meet Bingo
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body.h-full
    = render 'layouts/notices'

    - if current_user.present?
      .min-h-full
        nav.bg-gray-800
          .max-w-7xl.mx-auto.px-4.sm:px-6.lg:px-8
            .flex.items-center.justify-between.h-16
              .flex.items-center
                .flex-shrink-0
                  img[src="https://upload.wikimedia.org/wikipedia/commons/f/fb/Bingo_card_-_02.jpg" width="40" height="40"]
                .md:block
                  .ml-10.flex.items-baseline.space-x-4
                    = link_to 'My meetings', my_meetings_path, class: 'bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium', 'aria-current' => 'page'
                    / a.text-gray-300.hover:bg-gray-700.hover:text-white.px-3.py-2.rounded-md.text-sm.font-medium[href="#"]
                    /   | Team
              .md:block
                .ml-4.flex.items-center.md:ml-6
                  .ml-3.relative
                    div.text-gray-300
                      .welcome
                        = current_user.email
                      = link_to 'Sign out', sign_out_path
        = yield
    - else
      .bg-gray-100
        .max-w-7xl.mx-auto.py-12.px-4.sm:px-6.lg:px-8
          div
            h3.text-lg.leading-6.font-medium.text-gray-900
              | Sign in
            dl.mt-5.grid.grid-cols-1.gap-5.sm:grid-cols-2
              .px-4.py-5.bg-white.shadow.rounded-lg.overflow-hidden.sm:p-6
                = button_to "Log In with Google", "/auth/google_oauth2", 'data-turbo': 'false', class: "inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              - unless Rails.env.production?
                .px-4.py-5.bg-white.shadow.rounded-lg.overflow-hidden.sm:p-6
                  = button_to "Dev login", "/auth/developer", 'data-turbo': 'false', class: "inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"